---
title: "Vectors - Programming - Exercise"
author: "Marc A.T. Teunis"
date: "5/24/2017"
output:
  html_document:
    css: ~/hp_r_course/exercises/exercises_style.css
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

__Write an Rmd file, containing code chunks (if applicable) and answer all the questions below. Store the file in a folder called: "./answers_exercises" in your course project folder. Give this file the same name as the title of the current Rmd file__


1.  Describe the difference between `is.finite(x)` and  `!is.infinite(x)`.

1.  Read the source code for `dplyr::near()` (Hint: to see the source code,
    drop the `()`). How does it work? 

1.  A logical vector can take 3 possible values. How many possible
    values can an integer vector take? How many possible values can
    a double take? Use google to do some research.

1.  Brainstorm at least four functions that allow you to convert a double to an
    integer. How do they differ? Be precise.
    
1.  What functions from the readr package allow you to turn a string
    into logical, integer, and double vector?





## Using atomic vectors

Now that you understand the different types of atomic vector, it's useful to review some of the important tools for working with them. These include:

1.  How to convert from one type to another, and when that happens
    automatically.

1.  How to tell if an object is a specific type of vector.

1.  What happens when you work with vectors of different lengths.

1.  How to name the elements of a vector.

1.  How to pull out elements of interest.

### Coercion

There are two ways to convert, or coerce, one type of vector to another:

1.  Explicit coercion happens when you call a function like `as.logical()`,
    `as.integer()`, `as.double()`, or `as.character()`. Whenever you find
    yourself using explicit coercion, you should always check whether you can
    make the fix upstream, so that the vector never had the wrong type in 
    the first place. For example, you may need to tweak your readr 
    `col_types` specification.

1.  Implicit coercion happens when you use a vector in a specific context
    that expects a certain type of vector. For example, when you use a logical
    vector with a numeric summary function, or when you use a double vector
    where an integer vector is expected.


### Exercises

1.  What does `mean(is.na(x))` tell you about a vector `x`? What about
    `sum(!is.finite(x))`?

1.  Carefully read the documentation of `is.vector()`. What does it actually
    test for? Why does `is.atomic()` not agree with the definition of 
    atomic vectors above?
    
1.  Compare and contrast `setNames()` with `purrr::set_names()`.

1.  Create functions that take a vector as input and returns:
    
    1. The last value.  Should you use `[` or `[[`?

    1. The elements at even numbered positions.
    
    1. Every element except the last value.
    
    1. Only even numbers (and no missing values).

1.  Why is `x[-which(x > 0)]` not the same as `x[x <= 0]`? 

1.  What happens when you subset with a positive integer that's bigger
    than the length of the vector? What happens when you subset with a 
    name that doesn't exist?

